# config/meta.yml

meta_product_name: "Servicios de Dragados y Construcciones"
meta_title: "Servicios de Dragados y Construcciones"
meta_description: "SERDRAGA se dedica a proveer servicios de dragado y construcciones."
meta_image: "logo.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
